package pro.choicemmed.datalib;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CFT308_DATA".
*/
public class CFT308DataDao extends AbstractDao<CFT308Data, String> {

    public static final String TABLENAME = "CFT308_DATA";

    /**
     * Properties of entity CFT308Data.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Uuid = new Property(0, String.class, "uuid", true, "UUID");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property StartDate = new Property(2, String.class, "startDate", false, "START_DATE");
        public final static Property EndDate = new Property(3, String.class, "endDate", false, "END_DATE");
        public final static Property MeasureTime = new Property(4, String.class, "measureTime", false, "MEASURE_TIME");
        public final static Property Unit = new Property(5, String.class, "unit", false, "UNIT");
        public final static Property Temp = new Property(6, String.class, "temp", false, "TEMP");
        public final static Property AccountKey = new Property(7, String.class, "accountKey", false, "ACCOUNT_KEY");
        public final static Property UpLoadFlag = new Property(8, String.class, "upLoadFlag", false, "UP_LOAD_FLAG");
    }


    public CFT308DataDao(DaoConfig config) {
        super(config);
    }
    
    public CFT308DataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CFT308_DATA\" (" + //
                "\"UUID\" TEXT PRIMARY KEY NOT NULL ," + // 0: uuid
                "\"USER_ID\" TEXT," + // 1: userId
                "\"START_DATE\" TEXT," + // 2: startDate
                "\"END_DATE\" TEXT," + // 3: endDate
                "\"MEASURE_TIME\" TEXT," + // 4: measureTime
                "\"UNIT\" TEXT," + // 5: unit
                "\"TEMP\" TEXT," + // 6: temp
                "\"ACCOUNT_KEY\" TEXT," + // 7: accountKey
                "\"UP_LOAD_FLAG\" TEXT);"); // 8: upLoadFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CFT308_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CFT308Data entity) {
        stmt.clearBindings();
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(1, uuid);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(3, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(4, endDate);
        }
 
        String measureTime = entity.getMeasureTime();
        if (measureTime != null) {
            stmt.bindString(5, measureTime);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(6, unit);
        }
 
        String temp = entity.getTemp();
        if (temp != null) {
            stmt.bindString(7, temp);
        }
 
        String accountKey = entity.getAccountKey();
        if (accountKey != null) {
            stmt.bindString(8, accountKey);
        }
 
        String upLoadFlag = entity.getUpLoadFlag();
        if (upLoadFlag != null) {
            stmt.bindString(9, upLoadFlag);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CFT308Data entity) {
        stmt.clearBindings();
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(1, uuid);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(3, startDate);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(4, endDate);
        }
 
        String measureTime = entity.getMeasureTime();
        if (measureTime != null) {
            stmt.bindString(5, measureTime);
        }
 
        String unit = entity.getUnit();
        if (unit != null) {
            stmt.bindString(6, unit);
        }
 
        String temp = entity.getTemp();
        if (temp != null) {
            stmt.bindString(7, temp);
        }
 
        String accountKey = entity.getAccountKey();
        if (accountKey != null) {
            stmt.bindString(8, accountKey);
        }
 
        String upLoadFlag = entity.getUpLoadFlag();
        if (upLoadFlag != null) {
            stmt.bindString(9, upLoadFlag);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public CFT308Data readEntity(Cursor cursor, int offset) {
        CFT308Data entity = new CFT308Data( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // uuid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // startDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // endDate
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // measureTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // unit
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // temp
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // accountKey
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // upLoadFlag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CFT308Data entity, int offset) {
        entity.setUuid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStartDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEndDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMeasureTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUnit(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTemp(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAccountKey(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUpLoadFlag(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(CFT308Data entity, long rowId) {
        return entity.getUuid();
    }
    
    @Override
    public String getKey(CFT308Data entity) {
        if(entity != null) {
            return entity.getUuid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CFT308Data entity) {
        return entity.getUuid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
